import Head from 'next/head';
import { useSession, signIn, signOut } from 'next-auth/react';
import Login from '../components/login-btn';
import styles from '../styles/Home.module.css';

export default function Home() {
  const { data: session } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? (
        <>
          Signed in as {session.user.email} <br />
          <button onClick={() => signOut()}>Sign out</button>
        </>
      ) : (
        <>
          Not signed in <br />
          <button onClick={() => signIn()}>Sign in</button>
        </>
      )}
      <main className={styles.main}>
        <h1 className={styles.title}>
          <Login />
        </h1>
      </main>
    </div>
  );
}
