import Head from 'next/head';
import { useSession, signIn, signOut } from 'next-auth/react';
import NavbarTailwind from '../components/NavbarTailwind';
import styles from '../styles/Home.module.css';
import Card from '../components/Card';

export default function Home() {
  const { data: session } = useSession();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="sticky top-0">
        <NavbarTailwind />
      </div>

      <main className={styles.main}>
        <h1 className={styles.title}></h1>
        <Card />
      </main>
    </div>
  );
}
